function run_live_webcam_detection_testingv2(aslNet, inputSize)
    % Get available cameras
    camList = webcamlist;
    
    % Create camera selection dialog
    fSelection = uifigure('Name', 'Camera Selection', 'Position', [500 400 350 200], ...
                          'Color', [0.15 0.15 0.15]);
    
    uilabel(fSelection, ...
        'Position', [20 150 310 30], ...
        'Text', 'Select Camera for Sign Language Detection', ...
        'FontSize', 16, ...
        'FontColor', 'white', ...
        'HorizontalAlignment', 'center');
    
    cameraDropdown = uidropdown(fSelection, ...
        'Position', [50 110 250 30], ...
        'Items', camList, ...
        'Value', camList{1}, ...
        'FontSize', 14);
    
    uibutton(fSelection, ...
        'Position', [50 50 250 40], ...
        'Text', 'Start Detection', ...
        'ButtonPushedFcn', @(btn,event) startDetection(), ...
        'FontSize', 16, ...
        'BackgroundColor', [0.2 0.6 0.2], ...
        'FontColor', 'white');
    
    % Wait for user selection
    uiwait(fSelection);
    
    function startDetection()
        selectedCamera = cameraDropdown.Value;
        close(fSelection);
        
        % Initialize selected webcam
        cam = webcam(selectedCamera);
        
        % Create modern dark GUI window
        f = uifigure('Name', 'Live Sign Language Detection', 'Position', [100 100 900 650], ...
                     'Color', [0.15 0.15 0.15]);
        
        % Title banner with camera info
        uilabel(f, ...
            'Position', [0 580 900 70], ...
            'Text', sprintf('LIVE SIGN LANGUAGE DETECTION'), ...
            'FontSize', 24, ...
            'FontWeight', 'bold', ...
            'FontColor', [0.2 0.8 0.9], ...
            'BackgroundColor', [0.08 0.08 0.08], ...
            'HorizontalAlignment', 'center');

        % Camera panel
        camPanel = uipanel(f, 'Position', [30 160 500 400], ...
                          'Title', 'Camera Output', ...
                          'FontSize', 16, ...
                          'FontWeight', 'bold', ...
                          'ForegroundColor', [0.8 0.8 0.8], ...
                          'BackgroundColor', [0.1 0.1 0.1], ...
                          'HighlightColor', [0.3 0.3 0.3]);
        ax = uiaxes(camPanel, 'Position', [10 10 480 360]);
        ax.XColor = 'none';
        ax.YColor = 'none';
        ax.Toolbar.Visible = 'off';
        axis(ax, 'tight');

        % Results panel
        resultsPanel = uipanel(f, 'Position', [560 160 320 400], ...
                              'Title', 'Detection Results', ...
                              'FontSize', 16, ...
                              'FontWeight', 'bold', ...
                              'ForegroundColor', [0.8 0.8 0.8], ...
                              'BackgroundColor', [0.1 0.1 0.1], ...
                              'HighlightColor', [0.3 0.3 0.3]);
        
        % Prediction display
        predictionBox = uipanel(resultsPanel, ...
            'Position', [20 280 280 90], ...
            'BackgroundColor', [0.15 0.15 0.15], ...
            'BorderType', 'line', ...
            'HighlightColor', [0.2 0.7 0.9], ...
            'BorderWidth', 2);
        
        uilabel(predictionBox, ...
            'Position', [10 55 260 25], ...
            'Text', 'PREDICTED LETTER', ...
            'FontSize', 14, ...
            'FontColor', [0.7 0.7 0.7], ...
            'HorizontalAlignment', 'center');
        
        predictionLabel = uilabel(predictionBox, ...
            'Position', [10 10 260 45], ...
            'Text', '-', ...
            'FontSize', 36, ...
            'FontWeight', 'bold', ...
            'FontColor', [0.2 0.9 0.9], ...
            'HorizontalAlignment', 'center');
        
        % Confidence display
        confidenceBox = uipanel(resultsPanel, ...
            'Position', [20 180 280 80], ...
            'BackgroundColor', [0.15 0.15 0.15], ...
            'BorderType', 'line', ...
            'HighlightColor', [0.3 0.3 0.5], ...
            'BorderWidth', 2);
        
        uilabel(confidenceBox, ...
            'Position', [10 45 260 25], ...
            'Text', 'CONFIDENCE LEVEL', ...
            'FontSize', 14, ...
            'FontColor', [0.7 0.7 0.7], ...
            'HorizontalAlignment', 'center');
        
        confidenceLabel = uilabel(confidenceBox, ...
            'Position', [10 10 260 35], ...
            'Text', '0.0%', ...
            'FontSize', 24, ...
            'FontColor', [0.8 0.8 1], ...
            'HorizontalAlignment', 'center');
        
        % Status panel
        statusPanel = uipanel(resultsPanel, ...
            'Position', [20 50 280 110], ...
            'BackgroundColor', [0.15 0.15 0.15], ...
            'BorderType', 'line', ...
            'HighlightColor', [0.4 0.3 0.2], ...
            'BorderWidth', 2);
        
        uilabel(statusPanel, ...
            'Position', [10 80 260 25], ...
            'Text', 'SYSTEM STATUS', ...
            'FontSize', 14, ...
            'FontColor', [0.7 0.7 0.7], ...
            'HorizontalAlignment', 'center');
        
        statusLabel = uilabel(statusPanel, ...
            'Position', [10 45 260 35], ...
            'Text', 'Initializing...', ...
            'FontSize', 18, ...
            'FontColor', [1 0.8 0.3], ...
            'HorizontalAlignment', 'center');
        
        % User guidance
        uilabel(f, ...
            'Position', [30 130 500 20], ...
            'Text', 'Position your hand in the center of the frame for best results', ...
            'FontSize', 12, ...
            'FontColor', [0.8 0.8 0.8], ...
            'HorizontalAlignment', 'center');
        
        % Stop button
        btn = uibutton(f, ...
            'Text', 'Stop Detection', ...
            'Position', [360 80 180 50], ...
            'ButtonPushedFcn', @(btn,event) stopLoop(), ...
            'FontSize', 16, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [0.8 0.2 0.2], ...
            'FontColor', 'white');

        global continueLoop;
        continueLoop = true;
        
        % Initialization message
        statusLabel.Text = 'Initializing camera...';
        drawnow;
        pause(1);  % Brief pause to show initialization message
        statusLabel.Text = 'Detecting...';
        statusLabel.FontColor = [0.3 0.9 0.3];
        drawnow;
        
        while continueLoop && isvalid(f)
            % Capture frame
            frame = snapshot(cam);
            frame = imresize(frame, inputSize(1:2));
            
            % Classification
            [YPred, scores] = classify(aslNet, frame);
            confidence = max(scores) * 100;
            
            % Display original frame
            imshow(frame, 'Parent', ax);
            
            % Update prediction display
            predictionLabel.Text = char(YPred);
            
            % Update confidence with color coding
            confidenceLabel.Text = sprintf('%.1f%%', confidence);
            if confidence > 85
                confidenceLabel.FontColor = [0.3 1 0.3];  % Green for high confidence
            elseif confidence > 70
                confidenceLabel.FontColor = [1 1 0.3];     % Yellow for medium
            else
                confidenceLabel.FontColor = [1 0.4 0.3];   % Orange for low
            end
            
            drawnow limitrate; % Optimized for video display
        end

        % Cleanup
        clear cam;
        statusLabel.Text = 'Detection stopped';
        statusLabel.FontColor = [1 0.5 0.3];
        
        % Add delay before closing to show final message
        pause(1.5);
        if isvalid(f), close(f); end
    end
end

function stopLoop()
    global continueLoop;
    continueLoop = false;
end